import { Outfit } from 'next/font/google';
import './globals.css';
import Header from '@/Components/Header.jsx';
import Footer from '@/Components/Footer.jsx';

const outfit = Outfit({ subsets: ['latin'], weight: ['400', '500', '600', '700'] });

export const metadata = {
  title: 'Blog App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
